/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-west-3",
    "aws_cognito_identity_pool_id": "eu-west-3:e259ef52-eaeb-47c2-bb67-98cffc0a30c8",
    "aws_cognito_region": "eu-west-3",
    "aws_user_pools_id": "eu-west-3_RVDRNMgsb",
    "aws_user_pools_web_client_id": "6d98g6umq0l7s17fcaelj4iqjv",
    "oauth": {},
    "aws_cognito_username_attributes": [],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_appsync_graphqlEndpoint": "https://7ntujyz7svhclmmuulkruwvrdu.appsync-api.eu-west-3.amazonaws.com/graphql",
    "aws_appsync_region": "eu-west-3",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-aro4dic4q5gynlptj2oax5lxiq",
    "aws_user_files_s3_bucket": "s3amplify230206-dev",
    "aws_user_files_s3_bucket_region": "eu-west-3"
};


export default awsmobile;
